### ISSUE TITLE
Feedback on the current state of the tutorial

### ISSUE THREAD

**Issue by FlorianPargent** [lmu-osc/introduction-to-renv#15]
## Welcome to the {renv} Tutorial!

- [x] I would include a prominent link that brings you directly to the *Quick Start* page for people who want to skip the background (but might come back later)
- [x] Perhaps it would be a good idea to include links to all sections in the *Tutorial Overview*

## Reproducibility > What is Reproducibility?

- [x] I like that the tutorial starts with a general call to make research reproducible
- [x] However, at the end of "A brief definition" I would make it very clear what is the topic of this tutorial. Something like:

a) there is complete documentation of all materials that were used in the research project
b) there is documentation of the analyses
c) there is documentation of the code
d) there is documentation of the R and R package versions used to run the code. 

This tutorial only covers step d)

## Software Dependencies

- [x] #26

## Software Dependencies > Dependencies overview

- [x] I would explain that dependencies are also visible at the package website on cran. perhaps link to https://cran.r-project.org/web/packages/dplyr/index.html as an example
- [x] Perhaps place all the function calls (`utils::packageDescription()`, `pak::pkg_deps_tree()`, ...) into a collapsed callout box, because most novices wont use these functions on their first go and might be intimidated

## Technical Definitions > Packages

- [x] I think I would place the dplyr::filter code example in a collapsed callout box. I hope most readers will know how packages work (otherwise they will probably be greatly overwhelmed by renv)

## Technical Definitions > Pre-Installed Packages

- [x] I would hide the code to show the pre-installed packages in a collapsed callout box and only show the table

## Technical Definitions > Repositories

- [x] I would add links to CRAN and Bioconductor

## Dependency Management in R > Common Managers

- [x] I would put renv first and hide packrat and groundhog in a callout box

## Dependency Management in R > Limitations of Package Managers

- [x] In my experience, a soon as you start using renv, there will soon come the day when you need to switch between different R versions. I have only recently learned about rig and I think it is great. I would make the information about rig more prominent here (perhaps place it into a red callout box)
- [x] The *Posit Package Mangaer* link does not work.

## {renv}: Easy Start > Initiating {renv}

- [x] I did not know about `.Rbuildignore`. I guess that file is only relevant when you are working on an R package, right? I think I would not mention this file in the tutorial because it will not be relevant for our readership.
- [x] However, I would add a prominent link to the renv documentation (https://rstudio.github.io/renv/articles/renv.html#collaboration) or write a section in the tutorial in a collapsed callout box on which files you must add to git if you use git and renv for version control management 

## Caching

- [x] I think this page is quite technical and I am not sure whether it is really relevant for all readers. The people I think about usually are scared by folder stuff on their computer. I myself never had problems with the cache in renv and I think it usually just works and the average user does not have to know about any details here. I think I would move the complete page after *Restoring project* and perhaps mark it as more advanced content or even move it to *Optional content*?

## Restoring Another Project

- [x] #27

## Restoring Another Project > After Upgrading R

- [x] I would give this section another name like "Upgrading and updating" and focus not only on upgrading R but also on the common usecase that you go back to your own project and want to update all packages to the current version before you start working on the project again.
- [x] I would make the two functions renv::upgrade and renv::update more visible in this section by placing them in their own code chunks

## Alternative Workflow: `embed()` and `use()`

- [x] You write *"The downside to this approach is that caching is not available, and the packages are not tracked in a lockfile. This means that the versions of the packages are not guaranteed to be the same across different machines."* I think this is misleading because renv::embed will include the exact package version. So at least the package versions should also be documented correctly with this workflow.

**Comment by NeuroShepherd** [comment]
>  I would put renv first and hide packrat and groundhog in a callout box

I'm still opposed to this as I want readers to learn about some of the history/alternatives.

**Comment by NeuroShepherd** [comment]
>  Create table clarifying the inconsistent state possibilities and solutions

Turned this into a separate issue (and edited the text)
