### ISSUE TITLE
Background > Technical definitions: Use newer Bootstrap version for DT

### ISSUE THREAD

**Issue by fkohrt** [lmu-osc/introduction-to-renv#22]
When providing the `style = "bootstrap4"`, one can use a newer Bootstrap version for DT tables:

```r
DT::datatable(iris, style = "bootstrap4")
```

Relevant here:

https://github.com/lmu-osc/introduction-to-renv/blob/492a8ecee455fc15b82555e25b246274fe1816fb/technical_definitions.qmd#L38-L43

**Comment by fkohrt** [comment]
I think `bootstrap5` (unfortunately) is not a valid option so far, see rstudio/DT#964

**Comment by NeuroShepherd** [comment]
> I think `bootstrap5` (unfortunately) is not a valid option so far, see [rstudio/DT#964](https://github.com/rstudio/DT/issues/964)

 `DT::datable(style = "bootstrap5")` updates this `style` arg value regardless (because there's an internal check for the style, `grepl("^bootstrap", style)`) so I changed it in hopes that bootstrap5 will be made available some day
